# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{when_easter}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Michał Nierebiński}]
  s.date = %q{2011-06-28}
  s.description = %q{A tool that calculates the dates of Roman and Greek Easter.}
  s.email = %q{michal@nierebinski.pl}
  s.executables = [%q{when_easter}, %q{when_roman_easter}, %q{when_greek_easter}]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/when_easter",
    "lib/when_easter.rb",
    "when_easter.gemspec"
  ]
  s.homepage = %q{https://github.com/Loyolny/when_easter}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Get the date of Roman and Greek Easter}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

